# .circleci/config.yml
version: 2.1 
jobs:  
  build-image:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: arm.medium
    working_directory: ~/travis
    steps:
      - checkout
      - run: docker login -u luvjoey -p ${DOCKER_TOKEN}
      - run: docker build -t luvjoey/fedora_anaconda travis/fedora_anaconda
      - run: docker push luvjoey/fedora_anaconda
workflows:
  build:    
    jobs:      
      - build-image