# .circleci/config.yml
version: 2.1 
jobs:  
  build-image:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: arm.medium
    working_directory: ~/
    steps:      
      - run: docker pull fedora
      - run: docker images
      - run: pwd
      - run: tree
workflows:  
  build:    
    jobs:      
      - build-image